-- ============================================================
--  Run this script to add Phase 2 features to existing DB
--  sqlplus nayan/nayan@localhost:1521/XE @src/main/resources/db/new_tables.sql
-- ============================================================

BEGIN EXECUTE IMMEDIATE 'DROP TABLE COUPONS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE EXPENSES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE HOUSEKEEPING_LOG CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COUPON_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EXPENSE_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE SEQUENCE SEQ_COUPON_ID  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EXPENSE_ID START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE COUPONS (
    COUPON_ID        NUMBER        PRIMARY KEY,
    COUPON_CODE      VARCHAR2(30)  NOT NULL,
    DISCOUNT_PERCENT NUMBER(3)     NOT NULL,
    CUSTOMER_ID      NUMBER,
    BOOKING_REF      VARCHAR2(20),
    EXPIRY_DATE      DATE          NOT NULL,
    IS_USED          NUMBER(1)     DEFAULT 0,
    USED_DATE        DATE,
    CONSTRAINT uq_coupon_code UNIQUE (COUPON_CODE),
    CONSTRAINT fk_coupon_customer FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

CREATE OR REPLACE TRIGGER trg_coupons_bi
BEFORE INSERT ON COUPONS FOR EACH ROW
BEGIN
    IF :NEW.COUPON_ID IS NULL THEN
        SELECT SEQ_COUPON_ID.NEXTVAL INTO :NEW.COUPON_ID FROM DUAL;
    END IF;
END;
/

CREATE TABLE EXPENSES (
    EXPENSE_ID   NUMBER        PRIMARY KEY,
    TITLE        VARCHAR2(150) NOT NULL,
    CATEGORY     VARCHAR2(30)  NOT NULL,
    AMOUNT       NUMBER(12,2)  NOT NULL,
    EXPENSE_DATE DATE          DEFAULT SYSDATE,
    DESCRIPTION  VARCHAR2(500),
    APPROVED_BY  VARCHAR2(100),
    RECEIPT_REF  VARCHAR2(60)
);

CREATE OR REPLACE TRIGGER trg_expenses_bi
BEFORE INSERT ON EXPENSES FOR EACH ROW
BEGIN
    IF :NEW.EXPENSE_ID IS NULL THEN
        SELECT SEQ_EXPENSE_ID.NEXTVAL INTO :NEW.EXPENSE_ID FROM DUAL;
    END IF;
END;
/

CREATE TABLE HOUSEKEEPING_LOG (
    LOG_ID    NUMBER PRIMARY KEY,
    ROOM_ID   NUMBER NOT NULL,
    TASK_TYPE VARCHAR2(30),
    TASK_TIME DATE DEFAULT SYSDATE,
    CONSTRAINT fk_hk_room FOREIGN KEY (ROOM_ID) REFERENCES ROOMS(ROOM_ID)
);

CREATE SEQUENCE SEQ_HK_LOG START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER trg_hklog_bi
BEFORE INSERT ON HOUSEKEEPING_LOG FOR EACH ROW
BEGIN
    IF :NEW.LOG_ID IS NULL THEN
        SELECT SEQ_HK_LOG.NEXTVAL INTO :NEW.LOG_ID FROM DUAL;
    END IF;
END;
/

COMMIT;

SELECT 'COUPONS created' FROM DUAL;
SELECT 'EXPENSES created' FROM DUAL;
SELECT 'HOUSEKEEPING_LOG created' FROM DUAL;
