-- ============================================================
--  Customer Portal Tables  (Oracle 10g XE Compatible)
--  Uses BEFORE INSERT triggers for auto-increment (no DEFAULT NEXTVAL)
--  Run: sqlplus nayan/nayan@localhost:1521/XE @portal_tables.sql
-- ============================================================

-- Drop existing portal tables (safe re-run)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE FOOD_ORDER_ITEMS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE FOOD_ORDERS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SERVICE_REQUESTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CUSTOMER_ACCOUNTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE FOOD_MENU_ITEMS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Drop sequences
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CUST_ACCT_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_SVC_REQ_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_FOOD_ORDER_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_FOOD_ITEM_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MENU_ITEM_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Sequences
CREATE SEQUENCE SEQ_CUST_ACCT_ID  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SVC_REQ_ID    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FOOD_ORDER_ID START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FOOD_ITEM_ID  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MENU_ITEM_ID  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- CUSTOMER_ACCOUNTS
CREATE TABLE CUSTOMER_ACCOUNTS (
    ACCOUNT_ID      NUMBER          PRIMARY KEY,
    CUSTOMER_ID     NUMBER          NOT NULL UNIQUE,
    USERNAME        VARCHAR2(100)   NOT NULL UNIQUE,
    PASSWORD_HASH   VARCHAR2(200)   NOT NULL,
    ACTIVE          NUMBER(1)       DEFAULT 1 NOT NULL,
    CREATED_AT      DATE            DEFAULT SYSDATE,
    LAST_LOGIN      DATE,
    CONSTRAINT fk_cacct_customer FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMERS(CUSTOMER_ID)
);
/

CREATE OR REPLACE TRIGGER trg_cust_acct_bi
BEFORE INSERT ON CUSTOMER_ACCOUNTS FOR EACH ROW
BEGIN
    IF :NEW.ACCOUNT_ID IS NULL THEN
        SELECT SEQ_CUST_ACCT_ID.NEXTVAL INTO :NEW.ACCOUNT_ID FROM DUAL;
    END IF;
END;
/

-- SERVICE_REQUESTS
CREATE TABLE SERVICE_REQUESTS (
    REQUEST_ID      NUMBER          PRIMARY KEY,
    CUSTOMER_ID     NUMBER          NOT NULL,
    BOOKING_ID      NUMBER,
    REQUEST_TYPE    VARCHAR2(30)    NOT NULL,
    DESCRIPTION     VARCHAR2(500),
    PHONE_NUMBER    VARCHAR2(20),
    STATUS          VARCHAR2(20)    DEFAULT 'PENDING' NOT NULL,
    PRIORITY        VARCHAR2(10)    DEFAULT 'NORMAL',
    REQUESTED_AT    DATE            DEFAULT SYSDATE,
    COMPLETED_AT    DATE,
    NOTES           VARCHAR2(300),
    SEEN_BY_HOTEL   NUMBER(1)       DEFAULT 0,
    CONSTRAINT fk_svcreq_customer FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    CONSTRAINT fk_svcreq_booking  FOREIGN KEY (BOOKING_ID)  REFERENCES BOOKINGS(BOOKING_ID),
    CONSTRAINT chk_svc_type CHECK (REQUEST_TYPE IN (
        'HOUSEKEEPING','PHONE_CALL','EXTRA_TOWELS','EXTRA_PILLOW',
        'WAKE_UP_CALL','LAUNDRY','TAXI','GENERAL','MAINTENANCE')),
    CONSTRAINT chk_svc_status   CHECK (STATUS   IN ('PENDING','IN_PROGRESS','COMPLETED','CANCELLED')),
    CONSTRAINT chk_svc_priority CHECK (PRIORITY IN ('LOW','NORMAL','HIGH','URGENT'))
);
/

CREATE OR REPLACE TRIGGER trg_svc_req_bi
BEFORE INSERT ON SERVICE_REQUESTS FOR EACH ROW
BEGIN
    IF :NEW.REQUEST_ID IS NULL THEN
        SELECT SEQ_SVC_REQ_ID.NEXTVAL INTO :NEW.REQUEST_ID FROM DUAL;
    END IF;
END;
/

CREATE INDEX idx_svcreq_customer ON SERVICE_REQUESTS(CUSTOMER_ID);
CREATE INDEX idx_svcreq_status   ON SERVICE_REQUESTS(STATUS);
CREATE INDEX idx_svcreq_seen     ON SERVICE_REQUESTS(SEEN_BY_HOTEL);

-- FOOD_MENU_ITEMS
CREATE TABLE FOOD_MENU_ITEMS (
    MENU_ITEM_ID    NUMBER          PRIMARY KEY,
    ITEM_NAME       VARCHAR2(100)   NOT NULL,
    CATEGORY        VARCHAR2(30)    NOT NULL,
    DESCRIPTION     VARCHAR2(300),
    PRICE           NUMBER(10,2)    NOT NULL,
    AVAILABLE       NUMBER(1)       DEFAULT 1,
    PREP_TIME_MINS  NUMBER(3)       DEFAULT 20,
    CONSTRAINT chk_menu_cat CHECK (CATEGORY IN (
        'BREAKFAST','LUNCH','DINNER','SNACKS','BEVERAGES','DESSERTS','ROOM_SERVICE'))
);
/

CREATE OR REPLACE TRIGGER trg_menu_item_bi
BEFORE INSERT ON FOOD_MENU_ITEMS FOR EACH ROW
BEGIN
    IF :NEW.MENU_ITEM_ID IS NULL THEN
        SELECT SEQ_MENU_ITEM_ID.NEXTVAL INTO :NEW.MENU_ITEM_ID FROM DUAL;
    END IF;
END;
/

-- FOOD_ORDERS
CREATE TABLE FOOD_ORDERS (
    ORDER_ID        NUMBER          PRIMARY KEY,
    CUSTOMER_ID     NUMBER          NOT NULL,
    BOOKING_ID      NUMBER,
    ORDER_STATUS    VARCHAR2(20)    DEFAULT 'RECEIVED' NOT NULL,
    TOTAL_AMOUNT    NUMBER(12,2)    DEFAULT 0,
    SPECIAL_NOTES   VARCHAR2(300),
    ORDERED_AT      DATE            DEFAULT SYSDATE,
    DELIVERED_AT    DATE,
    SEEN_BY_HOTEL   NUMBER(1)       DEFAULT 0,
    CONSTRAINT fk_fordrs_customer FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    CONSTRAINT fk_fordrs_booking  FOREIGN KEY (BOOKING_ID)  REFERENCES BOOKINGS(BOOKING_ID),
    CONSTRAINT chk_ord_status CHECK (ORDER_STATUS IN (
        'RECEIVED','PREPARING','OUT_FOR_DELIVERY','DELIVERED','CANCELLED'))
);
/

CREATE OR REPLACE TRIGGER trg_food_order_bi
BEFORE INSERT ON FOOD_ORDERS FOR EACH ROW
BEGIN
    IF :NEW.ORDER_ID IS NULL THEN
        SELECT SEQ_FOOD_ORDER_ID.NEXTVAL INTO :NEW.ORDER_ID FROM DUAL;
    END IF;
END;
/

CREATE INDEX idx_fordrs_customer ON FOOD_ORDERS(CUSTOMER_ID);
CREATE INDEX idx_fordrs_status   ON FOOD_ORDERS(ORDER_STATUS);

-- FOOD_ORDER_ITEMS
CREATE TABLE FOOD_ORDER_ITEMS (
    ORDER_ITEM_ID   NUMBER          PRIMARY KEY,
    ORDER_ID        NUMBER          NOT NULL,
    MENU_ITEM_ID    NUMBER          NOT NULL,
    ITEM_NAME       VARCHAR2(100)   NOT NULL,
    QUANTITY        NUMBER(3)       NOT NULL,
    UNIT_PRICE      NUMBER(10,2)    NOT NULL,
    SUBTOTAL        NUMBER(10,2)    NOT NULL,
    CONSTRAINT fk_fitem_order FOREIGN KEY (ORDER_ID)     REFERENCES FOOD_ORDERS(ORDER_ID),
    CONSTRAINT fk_fitem_menu  FOREIGN KEY (MENU_ITEM_ID) REFERENCES FOOD_MENU_ITEMS(MENU_ITEM_ID)
);
/

CREATE OR REPLACE TRIGGER trg_food_item_bi
BEFORE INSERT ON FOOD_ORDER_ITEMS FOR EACH ROW
BEGIN
    IF :NEW.ORDER_ITEM_ID IS NULL THEN
        SELECT SEQ_FOOD_ITEM_ID.NEXTVAL INTO :NEW.ORDER_ITEM_ID FROM DUAL;
    END IF;
END;
/

-- ALTER BOOKINGS: add BOOKING_SOURCE and SEEN_BY_STAFF (safe re-run)
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE BOOKINGS ADD BOOKING_SOURCE VARCHAR2(20) DEFAULT ''STAFF'' NOT NULL';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE BOOKINGS ADD SEEN_BY_STAFF NUMBER(1) DEFAULT 1 NOT NULL';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Seed food menu (Full Las Vegas Luxury Menu - prices in USD)
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Truffle Scrambled Eggs with Brioche','BREAKFAST','Creamy scrambled eggs with shaved black truffle on toasted brioche',24,15);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Eggs Benedict with Smoked Salmon','BREAKFAST','Poached eggs, smoked salmon, hollandaise on English muffin',26,18);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Belgian Waffles with Berries and Cream','BREAKFAST','Crisp golden waffles topped with fresh berries and whipped cream',22,12);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Avocado Toast with Poached Eggs','BREAKFAST','Sourdough, smashed avocado, two poached eggs, micro herbs',18,10);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('French Toast with Maple Butter','BREAKFAST','Thick brioche French toast, maple syrup compound butter',20,12);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Shakshouka','BREAKFAST','Middle Eastern spiced tomato sauce with poached eggs, pita',19,15);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('English Breakfast Platter','BREAKFAST','Eggs, sausage, bacon, beans, mushroom, grilled tomato, toast',25,20);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Breakfast Burrito','BREAKFAST','Scrambled eggs, chorizo, peppers, cheese, salsa verde wrap',17,12);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Croissant Sandwich with Ham and Cheese','BREAKFAST','Buttery croissant, Black Forest ham, Gruyere, Dijon',16,8);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Acai Bowl with Granola','BREAKFAST','Blended acai, banana, granola, honey, seasonal fruits',18,8);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Grilled Chicken Caesar Salad','LUNCH','Romaine, parmesan, house Caesar dressing, anchovy croutons',22,15);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Margherita Pizza','LUNCH','San Marzano tomato, fresh buffalo mozzarella, basil, EVOO',24,20);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Sushi Bento Box','LUNCH','8-piece nigiri, miso soup, edamame, pickled ginger, wasabi',32,20);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Lobster Roll','LUNCH','New England style, cold lobster salad, brioche, drawn butter',38,18);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Chicken Shawarma Wrap','LUNCH','Marinated chicken, garlic sauce, pickles, tomato in flatbread',20,12);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Thai Green Curry with Rice','LUNCH','Coconut green curry, jasmine rice, Thai basil, kaffir lime',26,20);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Wagyu Burger with Fries','LUNCH','8oz wagyu patty, aged cheddar, truffle aioli, brioche bun',34,18);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Pasta Alfredo with Chicken','LUNCH','Fettuccine, grilled chicken, parmesan cream sauce',28,18);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Fish and Chips','LUNCH','Beer-battered cod, hand-cut fries, tartar sauce, mushy peas',27,20);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Steak Sandwich with Caramelized Onions','LUNCH','Sirloin, caramelized onions, horseradish cream, ciabatta',35,18);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Truffle Fries with Parmesan','SNACKS','Crispy fries, truffle oil, aged parmesan, fresh herbs',18,10);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Calamari Fritti','SNACKS','Golden fried squid, marinara, lemon aioli',24,12);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Nachos Supreme','SNACKS','Tortilla chips, pulled pork, guacamole, sour cream, pico',22,12);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Chicken Wings Buffalo or BBQ','SNACKS','12 wings, choice of sauce, celery, blue cheese dip',20,15);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Bruschetta Trio','SNACKS','Classic tomato, roasted pepper, mushroom-truffle on crostini',19,8);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Sliders Mini Burgers','SNACKS','3 mini wagyu sliders, special sauce, pickles',21,12);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Tempura Shrimp','SNACKS','6 tiger shrimp, light tempura batter, ponzu dipping sauce',26,12);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Cheese Platter European','SNACKS','Selection of aged cheeses, crackers, honey, dried fruits',30,5);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Garlic Bread with Cheese','SNACKS','Toasted sourdough, roasted garlic butter, melted mozzarella',15,8);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Spinach and Artichoke Dip','SNACKS','Creamy warm dip, tortilla chips, pita wedges',19,12);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Wagyu Steak Premium Cut','DINNER','10oz A5 wagyu ribeye, roasted garlic, bone marrow butter',120,30);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Grilled Salmon with Lemon Butter','DINNER','Atlantic salmon, lemon beurre blanc, asparagus, capers',48,22);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Lobster Thermidor','DINNER','Whole Maine lobster, brandy cream sauce, gratin topping',95,30);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Chicken Parmesan','DINNER','Pan-fried chicken, marinara, mozzarella, spaghetti al pomodoro',42,25);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Lamb Chops with Mint Sauce','DINNER','4 French-trimmed lamb chops, rosemary jus, mint gremolata',65,28);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Duck Breast with Red Wine Sauce','DINNER','Pan-seared magret duck, cherry-pinot noir reduction, dauphinoise',58,28);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Seafood Paella','DINNER','Saffron rice, lobster, shrimp, mussels, clams, chorizo',55,35);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Beef Wellington','DINNER','Beef tenderloin, mushroom duxelles, puff pastry, truffle jus',85,40);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Pasta Truffle Mushroom','DINNER','Fresh pappardelle, wild mushroom, truffle cream, parmesan',45,20);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Korean BBQ Platter','DINNER','Bulgogi beef, pork belly, kimchi, banchan, ssam wraps',70,30);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Classic Mojito','BEVERAGES','White rum, fresh mint, lime, sugar syrup, soda',16,5);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Margarita Premium Tequila','BEVERAGES','Patron silver, Cointreau, fresh lime, salted rim',18,5);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Old Fashioned','BEVERAGES','Woodford Reserve bourbon, Angostura bitters, orange peel',20,5);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Cosmopolitan','BEVERAGES','Absolut Citron, Cointreau, cranberry, fresh lime',17,5);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Espresso Martini','BEVERAGES','Kahlua, vodka, double espresso, coffee liqueur foam',19,5);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Champagne Glass','BEVERAGES','House Moet and Chandon Brut Imperial',22,2);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Craft Beer','BEVERAGES','Rotating selection of local and imported craft beers',10,2);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Fresh Juice Orange or Watermelon','BEVERAGES','Cold-pressed, no sugar added',9,5);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Iced Coffee Cold Brew','BEVERAGES','18-hour cold brew, house-made oat milk',8,3);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Mineral Water Imported','BEVERAGES','San Pellegrino or Acqua Panna 750ml',7,1);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('New York Cheesecake','DESSERTS','Classic NY style, graham cracker crust, berry coulis',14,5);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Chocolate Lava Cake','DESSERTS','Warm dark chocolate fondant, vanilla bean ice cream',16,15);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Tiramisu','DESSERTS','Savoiardi ladyfingers, mascarpone, espresso, cocoa dust',15,5);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Creme Brulee','DESSERTS','Classic French vanilla custard, caramelized sugar crust',15,8);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Macarons Assortment','DESSERTS','Box of 6 French macarons, rotating seasonal flavours',18,5);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Ice Cream Sundae','DESSERTS','3 scoops, hot fudge, whipped cream, cherry, wafer',13,5);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Apple Pie with Vanilla Ice Cream','DESSERTS','Warm spiced apple pie, house vanilla gelato',14,10);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Churros with Chocolate Dip','DESSERTS','Cinnamon sugar churros, Valrhona dark chocolate sauce',12,10);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Panna Cotta','DESSERTS','Italian vanilla panna cotta, passion fruit coulis',15,5);
INSERT INTO FOOD_MENU_ITEMS (ITEM_NAME,CATEGORY,DESCRIPTION,PRICE,PREP_TIME_MINS) VALUES ('Fruit Platter Deluxe','DESSERTS','Seasonal exotic fruits, honey yogurt dip, mint',17,5);

COMMIT;

SELECT 'CUSTOMER_ACCOUNTS  - OK' AS STATUS FROM DUAL;
SELECT 'SERVICE_REQUESTS   - OK' AS STATUS FROM DUAL;
SELECT 'FOOD_MENU_ITEMS    - OK' AS STATUS FROM DUAL;
SELECT 'FOOD_ORDERS        - OK' AS STATUS FROM DUAL;
SELECT 'FOOD_ORDER_ITEMS   - OK' AS STATUS FROM DUAL;
SELECT 'Portal setup complete!' AS STATUS FROM DUAL;

-- ═══════════════════════════════════════════════════════════
--  TABLE: AVAILABLE_SERVICES  (hotel-configured services)
-- ═══════════════════════════════════════════════════════════
BEGIN EXECUTE IMMEDIATE 'DROP TABLE AVAILABLE_SERVICES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_AVAIL_SVC_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE SEQUENCE SEQ_AVAIL_SVC_ID START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE AVAILABLE_SERVICES (
    SERVICE_ID      NUMBER          PRIMARY KEY,
    SERVICE_NAME    VARCHAR2(100)   NOT NULL,
    SERVICE_TYPE    VARCHAR2(30)    NOT NULL,
    DESCRIPTION     VARCHAR2(300),
    ICON            VARCHAR2(10)    DEFAULT '🔧',
    ACTIVE          NUMBER(1)       DEFAULT 1,
    CREATED_AT      DATE            DEFAULT SYSDATE
);
/

CREATE OR REPLACE TRIGGER trg_avail_svc_bi
BEFORE INSERT ON AVAILABLE_SERVICES FOR EACH ROW
BEGIN
    IF :NEW.SERVICE_ID IS NULL THEN
        SELECT SEQ_AVAIL_SVC_ID.NEXTVAL INTO :NEW.SERVICE_ID FROM DUAL;
    END IF;
END;
/

-- Seed default services
INSERT INTO AVAILABLE_SERVICES (SERVICE_NAME,SERVICE_TYPE,DESCRIPTION,ICON) VALUES ('Housekeeping','HOUSEKEEPING','Room cleaning and tidying service','🧹');
INSERT INTO AVAILABLE_SERVICES (SERVICE_NAME,SERVICE_TYPE,DESCRIPTION,ICON) VALUES ('Extra Towels','EXTRA_TOWELS','Request additional bath and hand towels','🛁');
INSERT INTO AVAILABLE_SERVICES (SERVICE_NAME,SERVICE_TYPE,DESCRIPTION,ICON) VALUES ('Extra Pillow','EXTRA_PILLOW','Request additional pillows or blankets','🛏');
INSERT INTO AVAILABLE_SERVICES (SERVICE_NAME,SERVICE_TYPE,DESCRIPTION,ICON) VALUES ('Wake-up Call','WAKE_UP_CALL','Schedule a morning wake-up call','⏰');
INSERT INTO AVAILABLE_SERVICES (SERVICE_NAME,SERVICE_TYPE,DESCRIPTION,ICON) VALUES ('Laundry','LAUNDRY','Laundry pickup and delivery service','👕');
INSERT INTO AVAILABLE_SERVICES (SERVICE_NAME,SERVICE_TYPE,DESCRIPTION,ICON) VALUES ('Taxi / Transfer','TAXI','Airport or city taxi arrangement','🚕');
INSERT INTO AVAILABLE_SERVICES (SERVICE_NAME,SERVICE_TYPE,DESCRIPTION,ICON) VALUES ('Maintenance','MAINTENANCE','Report a room maintenance issue','🔧');
INSERT INTO AVAILABLE_SERVICES (SERVICE_NAME,SERVICE_TYPE,DESCRIPTION,ICON) VALUES ('Phone Call','PHONE_CALL','Request staff to place a phone call from your room','📞');
INSERT INTO AVAILABLE_SERVICES (SERVICE_NAME,SERVICE_TYPE,DESCRIPTION,ICON) VALUES ('General Request','GENERAL','Any other request or inquiry','📋');

-- Add PHONE_CALL table for direct in-app calls
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PHONE_CALLS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PHONE_CALL_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE SEQUENCE SEQ_PHONE_CALL_ID START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE PHONE_CALLS (
    CALL_ID         NUMBER          PRIMARY KEY,
    CUSTOMER_ID     NUMBER          NOT NULL,
    CALLER_NAME     VARCHAR2(100),
    ROOM_NUMBER     VARCHAR2(10),
    CALL_STATUS     VARCHAR2(20)    DEFAULT 'RINGING' NOT NULL,
    CALLED_AT       DATE            DEFAULT SYSDATE,
    ANSWERED_AT     DATE,
    ANSWERED_BY     VARCHAR2(100),
    CONSTRAINT fk_call_customer FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    CONSTRAINT chk_call_status CHECK (CALL_STATUS IN ('RINGING','ANSWERED','MISSED','ENDED'))
);
/

CREATE OR REPLACE TRIGGER trg_phone_call_bi
BEFORE INSERT ON PHONE_CALLS FOR EACH ROW
BEGIN
    IF :NEW.CALL_ID IS NULL THEN
        SELECT SEQ_PHONE_CALL_ID.NEXTVAL INTO :NEW.CALL_ID FROM DUAL;
    END IF;
END;
/

COMMIT;
SELECT 'AVAILABLE_SERVICES - OK' AS STATUS FROM DUAL;
SELECT 'PHONE_CALLS        - OK' AS STATUS FROM DUAL;
